### ISSUE TITLE
s2i from software collections broken?

### ISSUE THREAD

**Issue by goern** [thoth-station/s2i-thoth-example#4]
Opened on behalf of @dfeddema

I'm using s2i from software collections (https://github.com/sclorg/s2i-python-container), after I copy the content of your .s2i directory to my git repo (https://github.com/dfeddema/mnist).
Looks like you must use a different version of s2i if this is working for you.  Please advise regarding which s2i tool I should be using. 
```
[root@gpu-compute-001 ~]# s2i build https://github.com/dfeddema/mnist rhscl/python-36-rhel7 python-tensorflow-sample-app-thoth

+ echo 'Checking if there is a need to lock dependencies...'

+ pushd /tmp/src

+ [[ -f Pipfile ]]

+ [[ ! -f Pipfile.lock ]]

+ echo 'Updating pip and installing Thamos...'

+ pip install --upgrade pip

Checking if there is a need to lock dependencies...

/tmp/src ~

Updating pip and installing Thamos...

Collecting pip

Downloading https://files.pythonhosted.org/packages/5c/e0/be401c003291b56efc55aeba6a80ab790d3d4cece2778288d65323009420/pip-19.1.1-py2.py3-none-any.whl (1.4MB)

Installing collected packages: pip

Found existing installation: pip 9.0.1

Uninstalling pip-9.0.1:

Successfully uninstalled pip-9.0.1

Successfully installed pip-19.1.1

+ pip3 install --upgrade setuptools

Collecting setuptools

Downloading https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl (575kB)

Installing collected packages: setuptools

Found existing installation: setuptools 28.8.0

Uninstalling setuptools-28.8.0:

Successfully uninstalled setuptools-28.8.0

Successfully installed setuptools-41.0.1

+ pip3 install git+https://github.com/thoth-station/invectio

Collecting git+https://github.com/thoth-station/invectio

Cloning https://github.com/thoth-station/invectio to /tmp/pip-req-build-4y_35h7i

  Running command git clone -q https://github.com/thoth-station/invectio /tmp/pip-req-build-4y_35h7i

Collecting click (from invectio==0.0.2)

Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)

Collecting daiquiri (from invectio==0.0.2)

Downloading https://files.pythonhosted.org/packages/a5/aa/31a81f03d8a6c8859706018ed1580fa2d2a16ee72976079d48139f28fd53/daiquiri-1.5.0-py2.py3-none-any.whl

Collecting attrs (from invectio==0.0.2)

Downloading https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl

Building wheels for collected packages: invectio

Building wheel for invectio (setup.py): started

Building wheel for invectio (setup.py): finished with status 'done'

Stored in directory: /tmp/pip-ephem-wheel-cache-o7bw2nyk/wheels/3a/6e/1e/069785e041b8e3e042e6a407da8b55450ac62f7fc768cd95fd

Successfully built invectio

Installing collected packages: click, daiquiri, attrs, invectio

Successfully installed attrs-19.1.0 click-7.0 daiquiri-1.5.0 invectio-0.0.2

+ pip3 install thamos

Collecting thamos

Downloading https://files.pythonhosted.org/packages/fb/83/2498416c1e84b307153c9003370d686820ba4ca2625133e8dbff7c2f68ec/thamos-0.4.2.tar.gz (41kB)

Collecting contoml (from thamos)

Downloading https://files.pythonhosted.org/packages/ff/0a/06d9b1e769493dcdf7bdee5725189aac52892dcc174c415b4fa873ed709a/contoml-0.32-py2.py3-none-any.whl (59kB)

Collecting certifi (from thamos)

Downloading https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl (158kB)

Collecting six (from thamos)

Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl

Collecting python_dateutil (from thamos)

Downloading https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl (226kB)

Requirement already satisfied: setuptools in /opt/app-root/lib/python3.6/site-packages (from thamos) (41.0.1)

Collecting urllib3 (from thamos)

Downloading https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl (150kB)

Requirement already satisfied: daiquiri in /opt/app-root/lib/python3.6/site-packages (from thamos) (1.5.0)

Requirement already satisfied: click in /opt/app-root/lib/python3.6/site-packages (from thamos) (7.0)

Collecting distro (from thamos)

Downloading https://files.pythonhosted.org/packages/ea/35/82f79b92fa4d937146c660a6482cee4f3dfa1f97ff3d2a6f3ecba33e712e/distro-1.4.0-py2.py3-none-any.whl

Collecting thoth-analyzer (from thamos)

Downloading https://files.pythonhosted.org/packages/3e/7c/0902aa7dd69acab7531e9bbfce4b893601ab58520697663ecdef174b3d37/thoth-analyzer-0.1.2.tar.gz

Collecting yaspin (from thamos)

Downloading https://files.pythonhosted.org/packages/d9/2c/c0b8ab9decf35e5770e0b7b20740b9bc114c5880e2af2c8ec6ca95637717/yaspin-0.14.3-py2.py3-none-any.whl

Collecting texttable (from thamos)

Downloading https://files.pythonhosted.org/packages/04/c6/7d2514d76fefba65bfe2fa4e1082c3adea9edef5a149a3027b8f2d5ee0eb/texttable-1.6.1.tar.gz

Collecting pyyaml (from thamos)

Downloading https://files.pythonhosted.org/packages/a3/65/837fefac7475963d1eccf4aa684c23b95aa6c1d033a2c5965ccb11e22623/PyYAML-5.1.1.tar.gz (274kB)

Collecting requests (from thamos)

Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)

Collecting termcolor (from thamos)

Downloading https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz

Requirement already satisfied: invectio in /opt/app-root/lib/python3.6/site-packages (from thamos) (0.0.2)

Collecting pytz (from contoml->thamos)

Downloading https://files.pythonhosted.org/packages/3d/73/fe30c2daaaa0713420d0382b16fbb761409f532c56bdcc514bf7b6262bb6/pytz-2019.1-py2.py3-none-any.whl (510kB)

Collecting timestamp (from contoml->thamos)

Downloading https://files.pythonhosted.org/packages/93/eb/0cb4c02285930822d623c8e31382a8b2d54be49b4dab0731e5986b8af0c5/timestamp-0.0.1.tar.gz

Collecting strict-rfc3339 (from contoml->thamos)

Downloading https://files.pythonhosted.org/packages/56/e4/879ef1dbd6ddea1c77c0078cd59b503368b0456bcca7d063a870ca2119d3/strict-rfc3339-0.7.tar.gz

Collecting iso8601 (from contoml->thamos)

Downloading https://files.pythonhosted.org/packages/ef/57/7162609dab394d38bbc7077b7ba0a6f10fb09d8b7701ea56fa1edc0c4345/iso8601-0.1.12-py2.py3-none-any.whl

Collecting delegator.py>=0.1.0 (from thoth-analyzer->thamos)

Downloading https://files.pythonhosted.org/packages/a7/c2/2860c52ef858c4672b6cf637f473e9139342cdb281135db9b3c32cfb0a85/delegator.py-0.1.1-py2.py3-none-any.whl

Collecting thoth-common (from thoth-analyzer->thamos)

Downloading https://files.pythonhosted.org/packages/b5/66/d670080bf2170524df0dd4f923cc50df617d40b4dc90b8e4647b27d4213a/thoth-common-0.8.11.tar.gz

Collecting chardet<3.1.0,>=3.0.2 (from requests->thamos)

Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)

Collecting idna<2.9,>=2.5 (from requests->thamos)

Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)

Requirement already satisfied: attrs in /opt/app-root/lib/python3.6/site-packages (from invectio->thamos) (19.1.0)

Collecting pexpect>=4.1.0 (from delegator.py>=0.1.0->thoth-analyzer->thamos)

Downloading https://files.pythonhosted.org/packages/0e/3e/377007e3f36ec42f1b84ec322ee12141a9e10d808312e5738f52f80a232c/pexpect-4.7.0-py2.py3-none-any.whl (58kB)

Collecting sentry-sdk (from thoth-common->thoth-analyzer->thamos)

Downloading https://files.pythonhosted.org/packages/5d/4b/b11147efdbb3844f5a986afee049830185579498382edb61f7ea62a9c5dc/sentry_sdk-0.9.0-py2.py3-none-any.whl (67kB)

Collecting rfc5424-logging-handler (from thoth-common->thoth-analyzer->thamos)

Downloading https://files.pythonhosted.org/packages/c5/45/c4393bb4cff2c5ad9bd836139cb9e4b6c39e787ef8a0e0a3b85a942b6581/rfc5424_logging_handler-1.4.3-py2.py3-none-any.whl

Collecting ptyprocess>=0.5 (from pexpect>=4.1.0->delegator.py>=0.1.0->thoth-analyzer->thamos)

Downloading https://files.pythonhosted.org/packages/d1/29/605c2cc68a9992d18dada28206eeada56ea4bd07a239669da41674648b6f/ptyprocess-0.6.0-py2.py3-none-any.whl

Collecting tzlocal (from rfc5424-logging-handler->thoth-common->thoth-analyzer->thamos)

Downloading https://files.pythonhosted.org/packages/cb/89/e3687d3ed99bc882793f82634e9824e62499fdfdc4b1ae39e211c5b05017/tzlocal-1.5.1.tar.gz

Building wheels for collected packages: thamos, thoth-analyzer, texttable, pyyaml, termcolor, timestamp, strict-rfc3339, thoth-common, tzlocal

Building wheel for thamos (setup.py): started

Building wheel for thamos (setup.py): finished with status 'done'

Stored in directory: /tmp/pip-ephem-wheel-cache-cl7el7y5/wheels/b7/c4/39/7717332816df1198195549ff379ec2ca8b896a6b3c8b466a20

Building wheel for thoth-analyzer (setup.py): started

Building wheel for thoth-analyzer (setup.py): finished with status 'done'

Stored in directory: /tmp/pip-ephem-wheel-cache-cl7el7y5/wheels/68/04/df/c8c3444c8bd06034b1026ba36f22fb36d62e62b6b7f9c8b231

Building wheel for texttable (setup.py): started

Building wheel for texttable (setup.py): finished with status 'done'

Stored in directory: /tmp/pip-ephem-wheel-cache-cl7el7y5/wheels/a7/4e/77/da46da4c5aece69b701cf45e6e4fe56ff98bfbdcc7b271d03b

Building wheel for pyyaml (setup.py): started

Building wheel for pyyaml (setup.py): finished with status 'done'

Stored in directory: /tmp/pip-ephem-wheel-cache-cl7el7y5/wheels/16/27/a1/775c62ddea7bfa62324fd1f65847ed31c55dadb6051481ba3f

Building wheel for termcolor (setup.py): started

Building wheel for termcolor (setup.py): finished with status 'done'

Stored in directory: /tmp/pip-ephem-wheel-cache-cl7el7y5/wheels/7c/06/54/bc84598ba1daf8f970247f550b175aaaee85f68b4b0c5ab2c6

Building wheel for timestamp (setup.py): started

Building wheel for timestamp (setup.py): finished with status 'done'

Stored in directory: /tmp/pip-ephem-wheel-cache-cl7el7y5/wheels/98/ce/47/81db33b7307eb75b3f752b1536d667af945059fd22e658245c

Building wheel for strict-rfc3339 (setup.py): started

Building wheel for strict-rfc3339 (setup.py): finished with status 'done'

Stored in directory: /tmp/pip-ephem-wheel-cache-cl7el7y5/wheels/bb/af/c9/b6e9fb5f9b2470e4ed2a7241c9ab3a8cdd3bc8555ae02ca2e6

Building wheel for thoth-common (setup.py): started

Building wheel for thoth-common (setup.py): finished with status 'done'

Stored in directory: /tmp/pip-ephem-wheel-cache-cl7el7y5/wheels/a9/33/7e/87c3118a2273f15ee410938b47d01c25480ab0aaf41797e5bb

Building wheel for tzlocal (setup.py): started

Building wheel for tzlocal (setup.py): finished with status 'done'

Stored in directory: /tmp/pip-ephem-wheel-cache-cl7el7y5/wheels/15/ae/df/a67bf1ed84e9bf230187d36d8dcfd30072bea0236cb059ed91

Successfully built thamos thoth-analyzer texttable pyyaml termcolor timestamp strict-rfc3339 thoth-common tzlocal

Installing collected packages: pytz, six, timestamp, strict-rfc3339, iso8601, contoml, certifi, python-dateutil, urllib3, distro, ptyprocess, pexpect, delegator.py, chardet, idna, requests, sentry-sdk, tzlocal, rfc5424-logging-handler, pyyaml, thoth-common, thoth-analyzer, yaspin, texttable, termcolor, thamos

Successfully installed certifi-2019.3.9 chardet-3.0.4 contoml-0.32 delegator.py-0.1.1 distro-1.4.0 idna-2.8 iso8601-0.1.12 pexpect-4.7.0 ptyprocess-0.6.0 python-dateutil-2.8.0 pytz-2019.1 pyyaml-5.1.1 requests-2.22.0 rfc5424-logging-handler-1.4.3 sentry-sdk-0.9.0 six-1.12.0 strict-rfc3339-0.7 termcolor-1.1.0 texttable-1.6.1 thamos-0.4.2 thoth-analyzer-0.1.2 thoth-common-0.8.11 timestamp-0.0.1 tzlocal-1.5.1 urllib3-1.25.3 yaspin-0.14.3

Performing hardware dicovery...

+ echo 'Performing hardware dicovery...'

+ thamos config --no-interactive

2019-06-13 02:40:03,258 [118] INFO     thamos: No configuration file found, creating one from a default configuration template

2019-06-13 02:40:03,258 [118] WARNING  thamos.config: Configuration file is not created in the root of git repo

2019-06-13 02:40:03,259 [118] CRITICAL root: Traceback (most recent call last):

  File "/opt/app-root/bin/thamos", line 10, in <module>

    sys.exit(cli())

  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 764, in __call__

    return self.main(*args, **kwargs)

  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 717, in main

    rv = self.invoke(ctx)

  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1137, in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 956, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 555, in invoke

    return callback(*args, **kwargs)

  File "/opt/app-root/lib/python3.6/site-packages/thamos/cli.py", line 483, in config

    configuration.create_default_config()

  File "/opt/app-root/lib/python3.6/site-packages/thamos/config.py", line 101, in create_default_config

    with open(self.DEFAULT_THOTH_CONFIG, "r") as default_config_file:

FileNotFoundError: [Errno 2] No such file or directory: '/opt/app-root/lib/python3.6/site-packages/thamos/data/defaultThoth.yaml'



Build failed

ERROR: An error occurred: non-zero (13) exit code from rhscl/python-36-rhel7
```

**Comment by goern** [comment]
I can confirm this bug for 's2i v1.0.9' using `registry.access.redhat.com/ubi8/python-36` or `rhscl/python-36-rhel7`.

**Comment by fridex** [comment]
I've just tested the s2i-thoth-example present in this repo. This issue was not spotted.

@dfeddema Is there available a build in a cluster I could try to debug?

**Comment by dfeddema** [comment]
@fridex I do have this set up on a cluster gpu-compute-001.infra.prod.upshift.rdu2.redhat.com.  I will send email with access info so you can run it there and reproduce this error yourself. 

I've done the following: 
1)  I tested the s2i-thoth-example (app.py) on gpu-compute-001.infra.prod.upshift.rdu2.redhat.com cluster and it worked for me. 
2)  I ran my original mnist code containerized with the Pipfile & PIpfile.lock and it worked correctly
Here's what that run looks like:
[root@gpu-compute-001 mnist]# time docker run -it python-tensorflow-sample-app
---> Running application from Python script (mnist.py) ...
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11493376/11490434 [==============================] - 0s 0us/step
WARNING:tensorflow:From /opt/app-root/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /opt/app-root/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py:143: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
2019-06-13 02:14:01.585941: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-06-13 02:14:01.594381: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2600000000 Hz
2019-06-13 02:14:01.601447: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x479a420 executing computations on platform Host. Devices:
2019-06-13 02:14:01.601529: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Epoch 1/5
60000/60000 [==============================] - 5s 91us/sample - loss: 0.2186 - acc: 0.9352
Epoch 2/5
60000/60000 [==============================] - 5s 90us/sample - loss: 0.0969 - acc: 0.9701
Epoch 3/5
60000/60000 [==============================] - 5s 90us/sample - loss: 0.0690 - acc: 0.9783
Epoch 4/5
60000/60000 [==============================] - 5s 90us/sample - loss: 0.0536 - acc: 0.9829
Epoch 5/5
60000/60000 [==============================] - 5s 89us/sample - loss: 0.0439 - acc: 0.9856
10000/10000 [==============================] - 0s 35us/sample - loss: 0.0572 - acc: 0.9817
real	0m30.220s
user	0m0.034s
sys	0m0.052s

3) I followed the instructions in the REAME here https://github.com/thoth-station/s2i-thoth-example
"copy content of .s2i directory present in this repository into your Git repository which is s2i enabled and remove Pipfile.lock from your repository" .  When I did this and re-ran s2i on my mnist repo I got error from software collections python s2i "ERROR: An error occurred: non-zero (13) exit code from rhscl/python-36-rhel7"

**Comment by goern** [comment]
@dfeddema I opened https://github.com/dfeddema/mnist/pull/1, this makes your repo build on PSI. Nevertheless there is an error dropped in the Thoth Backend:
```
---> Running application from script (app.sh) ...
--
  | Traceback (most recent call last):
  | File "thoth-adviser", line 37, in <module>
  | from thoth.adviser.python.exceptions import UnableLock
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/adviser/python/__init__.py", line 24, in <module>
  | from .dependency_monkey import dependency_monkey
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/adviser/python/dependency_monkey.py", line 35, in <module>
  | from .builder import PipelineBuilder
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/adviser/python/builder.py", line 30, in <module>
  | from .pipeline.steps import LimitLatestVersions
  | ModuleNotFoundError: No module named 'thoth.adviser.python.pipeline'
```

@fridex could you have a look at that pls.
